import 'package:flutter/widgets.dart';

class AppCopy {
  const AppCopy._();

  static const supportedLocales = [Locale('bn'), Locale('en')];

  static const Map<String, Map<String, String>> _values = {
    'en': {
      'welcome': 'Professional Astrology Workspace',
      'newConsultation': 'New Consultation',
      'clients': 'Clients',
      'vedic': 'Vedic / Parashari',
      'kp': 'KP Astrology',
      'kpWorkspace': 'KP Native Chart Workspace',
      'kpFoundationTitle': 'Governed KP Native Chart v4',
      'kpPointClassifier': 'Sign / star / sub classifier',
      'kpSiderealLongitude': 'Sidereal longitude (0°–<360°)',
      'kpLongitudeHelper': 'Enter an already-sidereal longitude for an independent Star/Sub review.',
      'kpClassifyPoint': 'Classify sign / star / sub',
      'kpRulingPlanets': 'Ruling planets — review profile',
      'kpAscendantLongitude': 'Ascendant sidereal longitude',
      'kpMoonLongitude': 'Moon sidereal longitude',
      'kpWeekday': 'Weekday at judgment moment',
      'kpBuildRulingPlanets': 'Build ruling-planet evidence',
      'kpCuspFramework': '12-cusp classification framework',
      'kpCuspLongitudes': '12 sidereal cusp longitudes',
      'kpCuspHelper': 'One longitude per line or comma-separated. This remains available as a manual cross-check beside native Placidus casting.',
      'kpClassifyCusps': 'Classify supplied cusps',
      'kpInvalidLongitude': 'Enter a valid sidereal longitude from 0 inclusive to 360 exclusive.',
      'kpInvalidCusps': 'Enter exactly 12 valid sidereal cusp longitudes.',
      'kpSourceSafetyNote': 'Native scope: governed KP ayanamsha, native Placidus cusps, planet/cusp Star/Sub, house occupancy/ownership, four-level significators, source-bounded Vimshottari DBA timing, Transit/Ruling-Planet confirmation, and separate query-time Horary RP corroboration for Marriage/Children. Horary RP corroboration does not reuse natal DBA or produce an exact future date.',
      'runKpNativeChart': 'Generate immutable KP native chart',
      'kpNativeRunning': 'Generating KP native chart…',
      'kpNativeReady': 'KP native chart snapshot saved',
      'kpNativeFailed': 'KP native chart could not be generated.',
      'kpSystemRequired': 'Select KP for this consultation to save a governed KP chart.',
      'kpNativeCasting': 'Native KP chart casting',
      'kpUtcDateTime': 'UTC date/time (ISO 8601)',
      'kpLatitude': 'Latitude',
      'kpLongitude': 'Longitude',
      'kpCastNativeChart': 'Cast native KP chart',
      'kpAyanamsha': 'Krishnamurti ayanamsha',
      'kpNativeChartFailed': 'Native KP chart casting failed.',
      'kpPlacidusNoFallback': 'Placidus is rejected in unsupported polar geometry; no Porphyry fallback is used.',
      'kpAdvancedSignificators': 'Advanced four-level significators',
      'kpEventReviewTopic': 'KP event-promise review',
      'kpEventMarriage': 'Marriage — 7th cusp / 2-7-11',
      'kpEventChildren': 'Children — 5th cusp / 2-5-11',
      'kpReviewEventEvidence': 'Review cusp sub-lord evidence',
      'kpEventState': 'KP review state',
      'kpDashaTiming': 'KP Vimshottari Dasha / Bhukti / Antara timing',
      'kpTimingGate': 'Timing gate',
      'kpSupportiveWindows': 'Supportive windows',
      'kpConflictingWindows': 'Conflicting windows',
      'kpCurrentDba': 'Current DBA',
      'kpNextSupportiveWindows': 'Next supportive windows',
      'kpNoSupportiveTiming': 'No supportive window is promoted under the current chart-promise gate.',
      'kpTimingSeparationNote': 'DBA timing remains the base layer. Transit and Ruling-Planet confirmation is evaluated separately and cannot rewrite the DBA state.',
      'kpTimingConfirmation': 'KP Transit + Ruling-Planet confirmation',
      'kpConfirmationState': 'Confirmation state',
      'kpConfidenceCeiling': 'Confidence ceiling',
      'kpRpOverlap': 'Fruitful standard RP overlap',
      'kpConfirmationSafetyNote': 'Transit/RP confirmation can raise the review ceiling only to Moderate. It does not guarantee an event or exact date.',
      'kpTimingConfirmationFailed': 'KP transit/Ruling-Planet confirmation could not be generated.',
      'kpHoraryTitle': 'KP Horary / Prashna — 1–249',
      'kpHoraryIntro': 'Use one clear question, a spontaneous number from 1–249, and the exact query moment/location. Natal birth details are not used.',
      'kpHoraryNumber': 'Horary number',
      'kpHoraryTopic': 'Question evidence profile',
      'kpHoraryGeneral': 'General — no automatic event judgment',
      'kpHoraryQuestion': 'Single horary question',
      'kpHoraryQuestionHelper': 'Keep one specific question per immutable snapshot.',
      'kpHoraryMomentLocationNote': 'The UTC/latitude/longitude fields above are the query moment and location. Planets use that moment; the number fixes the Horary Ascendant.',
      'kpHoraryCastSave': 'Cast & save immutable Horary snapshot',
      'kpHoraryAscendant': 'Horary Ascendant',
      'kpHoraryCuspError': 'Cusp-1 bind error',
      'kpHoraryCuspEvidence': 'Question-cusp evidence',
      'kpHoraryRpTiming': 'Query-time Ruling-Planet corroboration',
      'kpHoraryRpState': 'Horary timing corroboration',
      'kpHoraryPrimaryRpOverlap': 'Primary cusp sub-lord in standard RP set',
      'kpHoraryYes': 'Yes',
      'kpHoraryNo': 'No',
      'kpHoraryFruitfulRp': 'Fruitful standard RP planets',
      'kpHoraryMixedRp': 'Mixed standard RP planets',
      'kpHoraryDetrimentalRp': 'Detrimental-only standard RP planets',
      'kpHoraryConfidence': 'Horary confidence ceiling',
      'kpHoraryRpSafety': 'This is query-moment Ruling-Planet corroboration only. Natal DBA, birth data and future transit scanning are not used; no exact event date is generated.',
      'kpHoraryGeneralNoAutoJudgment': 'General Horary keeps the 12 cusps, planets, significators and Ruling Planets for practitioner review; no generic Promise/Denial formula is invented.',
      'kpHorarySnapshot': 'Saved snapshot ID',
      'kpHorarySavedTotal': 'Saved Horary snapshots',
      'kpHorarySafetyNote': 'The technical UTC used to solve Placidus cusp geometry is not an event time. Horary output is practitioner-review material, not a guaranteed yes/no outcome.',
      'kpHoraryFailed': 'KP Horary chart could not be generated or saved.',

      'weekday1': 'Monday',
      'weekday2': 'Tuesday',
      'weekday3': 'Wednesday',
      'weekday4': 'Thursday',
      'weekday5': 'Friday',
      'weekday6': 'Saturday',
      'weekday7': 'Sunday',
      'western': 'Western Astrology',
      'westernWorkspace': 'Western Natal Chart Workspace',
      'westernFoundationTitle': 'Western Astrology Modern Evidence v2',
      'westernFoundationDisclosure': 'Tropical chart evidence for professional review. Rulership, aspect, modern-planet and pattern profiles are stored with the output; no automatic event prediction or cross-system confidence uplift is generated.',
      'westernUtcDateTime': 'UTC date/time (ISO 8601)',
      'westernLatitude': 'Latitude',
      'westernLongitude': 'Longitude',
      'westernHouseSystemLabel': 'House system',
      'westernNodeModeLabel': 'Lunar node mode',
      'westernCastChart': 'Cast Western natal chart',
      'westernChartRunning': 'Generating Western natal chart…',
      'westernChartReady': 'Western natal chart snapshot saved',
      'westernChartFailed': 'Western natal chart could not be generated.',
      'westernSystemRequired': 'Select Western Astrology for this consultation to save a governed Western chart.',
      'westernAscMc': 'Ascendant / Midheaven',
      'westernPlanetsHouses': 'Tropical planets & houses',
      'westernMajorAspects': 'Major aspects',
      'westernNoMajorAspects': 'No aspect falls inside the governed major-aspect orb profile.',
      'westernRulershipProfileLabel': 'Rulership profile',
      'westernRulership_traditional': 'Traditional rulership',
      'westernRulership_modern': 'Modern rulership',
      'westernAspectProfileLabel': 'Aspect profile',
      'westernAspectProfile_majorOnly': 'Major only',
      'westernAspectProfile_majorAndMinor': 'Major + governed minor',
      'westernModernPlanets': 'Modern planets — native astronomical positions',
      'westernModernPlanetsDisabled': 'Modern-planet output is disabled for this chart.',
      'westernPlanetColumn': 'Planet',
      'westernLongitudeColumn': 'Longitude',
      'westernLatitudeColumn': 'Latitude',
      'westernHouseColumn': 'House',
      'westernAspects': 'Aspect evidence table',
      'westernNoAspects': 'No aspect falls inside the selected governed orb profile.',
      'westernAspectPairColumn': 'Planets',
      'westernAspectColumn': 'Aspect',
      'westernOrbColumn': 'Orb / limit',
      'westernMotionColumn': 'Motion',
      'westernAspectPatterns': 'Aspect pattern evidence',
      'westernNoAspectPatterns': 'No governed aspect pattern is present.',
      'westernPatternEvidenceNote': 'Patterns retain their component planets, aspects and orb evidence. Loose geometry does not create a pattern and no life-event prediction is generated.',
      'westernRulerships': 'Sign rulership evidence',
      'westernDignities': 'Traditional essential dignity evidence',
      'westernNoDignity': 'No domicile/exaltation/detriment/fall condition',
      'westernDignitySeparationNote': 'Modern sign rulers do not alter the authoritative traditional domicile/exaltation/detriment/fall evidence.',
      'westernAspectOrbNote': 'Aspect orbs are a versioned ASTRO LOGIC operating profile, not a universal historical standard.',
      'westernPlacidusNoFallback': 'Unsupported Placidus polar geometry is rejected; Whole Sign or Equal must be selected explicitly rather than substituted silently.',
      'westernScopeNote': 'v2 adds native Uranus, Neptune and Pluto, explicit rulership profiles, optional minor aspects and deterministic pattern evidence. Traditional essential dignity remains restricted to the seven traditional planets; triplicity, terms and faces remain outside this profile.',
      'uranus': 'Uranus',
      'neptune': 'Neptune',
      'pluto': 'Pluto',
      'semisextile': 'Semisextile',
      'semisquare': 'Semisquare',
      'quintile': 'Quintile',
      'sesquiquadrate': 'Sesquiquadrate',
      'quincunx': 'Quincunx / Inconjunct',
      'grandTrine': 'Grand Trine',
      'tSquare': 'T-Square',
      'grandCross': 'Grand Cross',
      'stellium': 'Stellium',
      'yod': 'Yod',
      'kite': 'Kite',
      'northNode': 'North Node',
      'southNode': 'South Node',
      'conjunction': 'Conjunction',
      'sextile': 'Sextile',
      'square': 'Square',
      'trine': 'Trine',
      'opposition': 'Opposition',
      'applying': 'Applying',
      'separating': 'Separating',
      'domicile': 'Domicile',
      'exaltation': 'Exaltation',
      'detriment': 'Detriment',
      'fall': 'Fall',
      'numerology': 'Numerology',
      'numerologyWorkspace': 'Numerology Consultation Workspace',
      'numerologyIntro': 'Enter the exact Latin spelling and birth date to generate an offline professional-review profile.',
      'latinNameForCalculation': 'Exact English / Latin name spelling',
      'exactSpellingNote': 'The app will not transliterate or change this spelling automatically.',
      'alternateSpellings': 'Alternate spellings to compare',
      'alternateSpellingsHint': 'One English / Latin spelling per line (maximum 8). The engine compares but never ranks them.',
      'nameCandidateComparison': 'Alternate-name arithmetic comparison',
      'professionalNameFocus': 'Professional discussion focus',
      'professionalNameFocusNone': 'No candidate selected',
      'professionalNameFocusAction': 'Mark for professional discussion',
      'professionalNameFocusClear': 'Clear professional focus',
      'nameCandidateSafety': 'Arithmetic comparison only — no best/lucky-name ranking or automatic name-change recommendation.',
      'numerologySpellingInvalid': 'Use only English letters, spaces, period, hyphen or apostrophe.',
      'selectBirthDate': 'Select birth date',
      'personalYearTarget': 'Personal Year target',
      'calculateNumerology': 'Calculate and review Numerology',
      'numerologyCalculationFailed': 'Numerology calculation could not be completed.',
      'calculationBreakdown': 'Verified calculation breakdown',
      'driverNumber': 'Driver / Birth',
      'lifePathNumber': 'Life Path',
      'maturityNumber': 'Maturity synthesis',
      'personalYearNumber': 'Personal Year',
      'pythagoreanExpression': 'Pythagorean Expression',
      'soulUrgeNumber': 'Soul Urge',
      'personalityNumber': 'Personality',
      'chaldeanNameNumber': 'Chaldean Name',
      'calculationEvidence': 'Calculation evidence and rule IDs',
      'strengthsChallenges': 'Strengths and review tendencies',
      'personalYearWindow': 'Three-year Personal Year context',
      'vedicCrossCheck': 'Guarded Vedic cross-check',
      'numerologyPredictionConfidence': 'Prediction confidence policy',
      'numerologyRemedyReview': 'Behavioural remedy candidate',
      'numerologyWarnings': 'Numerology scope and safety warnings',
      'runNumerologyAnalysis': 'Open Numerology analysis',
      'numerologySystemRequired': 'Select Numerology for this consultation to save a governed profile.',
      'saveNumerologySnapshot': 'Save immutable Numerology snapshot',
      'numerologySnapshotSaving': 'Saving immutable snapshot…',
      'numerologySnapshotSaved': 'Numerology snapshot saved offline',
      'savedNumerologySnapshots': 'Saved Numerology snapshots',
      'numerologyImmutableNote': 'Saved versions are permanent, hash-protected and cannot be edited or deleted.',
      'noNumerologySnapshots': 'No Numerology snapshot has been saved for this consultation.',
      'snapshotHash': 'Snapshot SHA-256',
      'numerologySnapshotCreated': 'Numerology snapshot created',
      'vastu': 'Vastu',
      'palmistry': 'Palmistry',
      'gemstoneRemedies': 'Gemstone Remedies',
      'reports': 'Reports',
      'practice': 'Practice',
      'settings': 'Calculation settings',
      'offline': 'Offline and private',
      'comingSoon': 'Module foundation ready',
      'addClient': 'Add client',
      'searchClients': 'Search clients',
      'noClients': 'No clients registered yet',
      'clientDetails': 'Client details',
      'fullName': 'Full name',
      'mobile': 'Mobile number',
      'email': 'Email (optional)',
      'gender': 'Gender',
      'male': 'Male',
      'female': 'Female',
      'other': 'Other / Prefer not to say',
      'notes': 'Professional notes (optional)',
      'birthDetails': 'Birth details',
      'birthLabel': 'Record label',
      'birthDate': 'Birth date',
      'birthTime': 'Birth time',
      'birthPlace': 'Birth place',
      'latitude': 'Latitude',
      'longitude': 'Longitude',
      'utcOffset': 'UTC offset at birth',
      'timeConfidence': 'Birth-time confidence',
      'exact': 'Exact',
      'recorded': 'Recorded',
      'approximate': 'Approximate',
      'unknown': 'Unknown',
      'sourceNote': 'Birth-time source / note',
      'save': 'Save client',
      'required': 'Required',
      'invalidNumber': 'Enter a valid number',
      'invalidLatitude': 'Latitude must be between -90 and 90',
      'invalidLongitude': 'Longitude must be between -180 and 180',
      'futureDate': 'Birth date cannot be in the future',
      'saved': 'Client saved offline',
      'birthRecord': 'Primary birth record',
      'databaseError': 'Could not save. Please try again.',
      'edit': 'Edit',
      'clientProfile': 'Client profile',
      'birthRecords': 'Birth records',
      'addBirthRecord': 'Add birth record',
      'editBirthRecord': 'Edit birth record',
      'localTime': 'Local civil time',
      'utcTime': 'Calculated UTC',
      'coordinates': 'Coordinates',
      'updated': 'Changes saved offline',
      'ayanamsha': 'Default ayanamsha',
      'lahiri': 'Lahiri',
      'raman': 'Raman',
      'krishnamurti': 'Krishnamurti',
      'vedicChartStyle': 'Vedic chart style',
      'northIndian': 'North Indian',
      'southIndian': 'South Indian',
      'eastIndian': 'East Indian',
      'westernHouseSystem': 'Western house system',
      'placidus': 'Placidus',
      'wholeSign': 'Whole Sign',
      'equal': 'Equal House',
      'lunarNodeMode': 'Rahu/Ketu calculation',
      'trueNode': 'True nodes',
      'meanNode': 'Mean nodes',
      'settingsNote': 'These defaults are stored with every future calculation snapshot.',
      'saveSettings': 'Save calculation settings',
      'refresh': 'Refresh',
      'importLedgerTitle': 'Backup import batch ledger',
      'importLedgerIntro': 'Durable local history of governed backup merges. Each committed batch binds the source manifest to source/local ID mappings and an exportable receipt hash. Failed or interrupted attempts retain diagnostics without retaining partial imported rows.',
      'importLedgerEmpty': 'No governed backup merge batches have been recorded yet.',
      'importBatch': 'Import batch',
      'importBatchStatus': 'Status',
      'importBatchStarted': 'Started UTC',
      'importBatchCompleted': 'Completed UTC',
      'importBatchSource': 'Source app / engine',
      'importBatchSchema': 'Source schema',
      'importBatchMappings': 'Source → local mappings',
      'importBatchReceiptHash': 'Merge receipt SHA-256',
      'importBatchDiagnostics': 'Recovery diagnostics',
      'importBatchCommitted': 'Committed',
      'importBatchFailed': 'Failed / rolled back',
      'importBatchStartedStatus': 'Incomplete / started',
      'viewMappings': 'View ID mappings',
      'exportMergeReceipt': 'Export merge receipt',
      'mergeReceiptFailed': 'Merge receipt could not be exported or its ledger hash did not verify.',
      'noImportMappings': 'No committed source/local mappings are stored for this batch.',
      'mappingSourceId': 'Source ID',
      'mappingLocalId': 'Local ID',
      'mappingResolution': 'Resolution',
      'mapping_inserted': 'Inserted with source ID',
      'mapping_equivalent': 'Equivalent local row reused',
      'mapping_remapped': 'Primary key remapped',
      'mappingSourceHash': 'Source-row SHA-256',
      'mappingLocalHash': 'Local-row SHA-256',
      'backupRestore': 'Encrypted backup & restore',
      'backupRestoreTitle': 'Encrypted backup & restore',
      'encryptedBackupTitle': 'Password-protected encrypted backup',
      'encryptedBackupIntro': 'Create a portable offline backup of clients, birth records, consultations, settings, audit history and all governed calculation, analysis, report and approval records.',
      'encryptedBackupCryptoDisclosure': 'Backup v1 uses Argon2id password key derivation and AES-256-GCM authenticated encryption. The password is never stored in the backup or database.',
      'createEncryptedBackup': 'Create encrypted backup',
      'restoreEncryptedBackup': 'Restore encrypted backup',
      'restoreEmptyWorkspaceOnly': 'Encrypted restore, governed non-empty merge, conflict planning and durable import-batch ledger.',
      'restoreNoMergeWarning': 'Existing records are never overwritten. Governed merge can reuse equivalent rows and deterministically remap primary-key collisions while preserving immutable source identities.',
      'selectBackupAndRestore': 'Select .albackup file and restore',
      'restorePreviewTitle': 'Restore preview & conflict planner',
      'restorePreviewIntro': 'Decrypt and validate a backup before any database mutation. Source version, schema, table counts, integrity and same-ID conflicts are shown first.',
      'selectBackupAndPreview': 'Select .albackup file and preview',
      'restorePreviewedBackup': 'Restore this verified backup',
      'restoreBlockedByPlanner': 'The preview planner has blocked execution because this backup is not eligible for either empty restore or governed merge.',
      'restorePreviewCompleted': 'Backup decrypted and previewed without database mutation.',
      'restorePreviewFailed': 'Backup preview could not be completed.',
      'restorePreviewVerified': 'Pre-restore verification result',
      'previewSourceApp': 'Source app version',
      'previewBackupEngine': 'Backup engine version',
      'previewSourceSchema': 'Source database schema',
      'previewBackupCreated': 'Backup created UTC',
      'previewManifestIntegrity': 'Manifest integrity',
      'previewSnapshotIntegrity': 'Governed snapshot integrity',
      'previewIncomingRows': 'Incoming protected rows',
      'previewLocalSensitiveRows': 'Existing governed local rows',
      'previewDatabaseMutation': 'Database mutation during preview',
      'previewMergeExecution': 'Governed merge/remap',
      'previewEligible': 'Eligible: current schema + empty workspace. Restore may proceed after password re-entry.',
      'previewBlockedNonEmpty': 'Blocked: this backup cannot be safely merged into the current workspace.',
      'previewRequiresMigration': 'Migration required: backup schema differs from the current app schema. Restore is disabled.',
      'previewUnsupported': 'Unsupported backup for this app version.',
      'previewTableCounts': 'Backup table counts',
      'previewConflictPlan': 'Table-by-table ID conflict plan',
      'previewIncoming': 'Incoming',
      'previewLocal': 'Local',
      'previewNewIds': 'New IDs',
      'previewEquivalentIds': 'Equivalent IDs',
      'previewConflictingIds': 'Unresolved conflicts',
      'previewRemappedIds': 'Remapped IDs',
      'previewMergeEligible': 'Eligible: governed merge can run transactionally without overwriting local records.',
      'mergePreviewedBackup': 'Merge this verified backup',
      'mergeConfirmTitle': 'Governed merge into this workspace?',
      'mergeConfirmMessage': 'Equivalent rows will be reused, primary-key collisions will be deterministically remapped, and immutable source IDs/hashes will be preserved. Any validation or insertion failure rolls back the entire transaction.',
      'mergeCompleted': 'Governed backup merge completed and verified.',
      'mergeFailed': 'Governed backup merge could not be completed. No partial merge is retained.',
      'mergeVerified': 'Governed merge completed after integrity verification',
      'mergeInsertedRows': 'Inserted rows',
      'mergeEquivalentSkipped': 'Equivalent rows reused',
      'mergeRemappedRows': 'Remapped rows',
      'mergeRollbackPolicy': 'Rollback policy',
      'enabled': 'Enabled',
      'verified': 'Verified',
      'notVerified': 'Not verified',
      'requiresMigrationReview': 'Not run — schema migration review required',
      'nonePerformed': 'None',
      'disabled': 'Disabled',
      'backupRestoreWorking': 'Encrypting, validating or restoring data…',
      'backupPasswordCreateTitle': 'Create backup password',
      'backupPasswordEnterTitle': 'Enter backup password',
      'backupPassword': 'Backup password',
      'confirmBackupPassword': 'Confirm backup password',
      'backupPasswordRule': 'Use at least 12 characters. A longer unique passphrase is strongly preferred.',
      'backupPasswordTooShort': 'Password must contain at least 12 characters.',
      'backupPasswordMismatch': 'The two passwords do not match.',
      'passwordNotStoredWarning': 'ASTRO LOGIC does not store or recover this password. If it is lost, this backup cannot be decrypted.',
      'backupCreated': 'Encrypted backup created and integrity manifest sealed',
      'backupCreateFailed': 'Encrypted backup could not be created.',
      'backupShareNote': 'ASTRO LOGIC encrypted backup. Keep the password separate from the backup file.',
      'backupManifestHash': 'Manifest SHA-256',
      'backupFileHash': 'Encrypted file SHA-256',
      'backupRecordCount': 'Protected rows',
      'backupFileReadFailed': 'The selected backup file could not be read.',
      'backupFileTooLarge': 'The selected backup exceeds the 128 MiB v1 size limit.',
      'restoreConfirmTitle': 'Restore protected data?',
      'restoreConfirmMessage': 'Restore will proceed only if this workspace is empty. The file must authenticate with the correct password and every manifest/hash/foreign-key check must pass.',
      'restoreCompleted': 'Encrypted backup restored and verified offline.',
      'restoreFailed': 'Encrypted backup could not be restored.',
      'restoreVerified': 'Restore completed after integrity verification',
      'importedAuditEvents': 'Imported audit events',
      'cancel': 'Cancel',
      'continueAction': 'Continue',
      'history': 'Audit history',
      'snapshots': 'Calculation snapshots',
      'createSnapshot': 'Freeze input snapshot',
      'snapshotCreated': 'Immutable input snapshot created',
      'inputHash': 'SHA-256 input hash',
      'schemaVersion': 'Schema version',
      'clientCreated': 'Client created',
      'clientUpdated': 'Client updated',
      'birthRecordCreated': 'Birth record created',
      'birthRecordUpdated': 'Birth record updated',
      'settingsUpdated': 'Calculation settings updated',
      'noHistory': 'No audit events available',
      'noSnapshots': 'No calculation snapshots yet',
      'immutableNote': 'Snapshots are permanent and cannot be edited or deleted.',
      'consultations': 'Consultations',
      'consultationSubject': 'Question / consultation subject',
      'consultationCategory': 'Category',
      'selectBirthRecord': 'Select birth record',
      'selectSystems': 'Select astrology systems',
      'general': 'General',
      'career': 'Career',
      'business': 'Business',
      'marriage': 'Marriage',
      'finance': 'Finance',
      'education': 'Education',
      'health': 'Health',
      'property': 'Property',
      'children': 'Children',
      'travelRelocation': 'Travel / Relocation',
      'draft': 'Draft',
      'reviewed': 'Reviewed',
      'finalized': 'Finalized',
      'selectAtLeastOne': 'Select at least one astrology system',
      'consultationCreated': 'Consultation created',
      'consultationUpdated': 'Consultation updated',
      'calculationOutputCreated': 'Versioned calculation output created',
      'noConsultations': 'No consultations yet',
      'enginePending': 'Calculation engine output pending',
      'consultationDetails': 'Consultation details',
      'editConsultation': 'Edit consultation',
      'prepareInput': 'Prepare calculation input',
      'inputReady': 'Calculation input snapshot is ready',
      'idempotentInputNote': 'Unchanged birth data and settings reuse the existing snapshot.',
      'calculationOutputs': 'Calculation outputs',
      'outputAvailable': 'Verified calculation output available',
      'engineVersion': 'Engine version',
      'outputHash': 'Output SHA-256 hash',
      'reviewRequiresOutput': 'A verified engine output is required before review.',
      'markReviewed': 'Mark as reviewed',
      'reopenDraft': 'Reopen as draft',
      'finalizeConsultation': 'Finalize consultation',
      'finalizedLocked': 'Finalized consultation is locked',
      'statusUpdated': 'Consultation status updated',
      'invalidTransition': 'This status change is not permitted',
      'calculatedFieldsLocked': 'Birth record and selected systems are locked after calculation.',
      'addGemstoneRemedy': 'Add gemstone remedy',
      'editGemstoneRemedy': 'Edit gemstone remedy',
      'noGemstoneRemedies': 'No gemstone remedies recorded yet',
      'planet': 'Target planet',
      'sun': 'Sun',
      'moon': 'Moon',
      'mars': 'Mars',
      'mercury': 'Mercury',
      'jupiter': 'Jupiter',
      'venus': 'Venus',
      'saturn': 'Saturn',
      'rahu': 'Rahu',
      'ketu': 'Ketu',
      'primaryGemstone': 'Primary gemstone',
      'substituteGemstone': 'Substitute gemstone (optional)',
      'gemstoneWeight': 'Weight',
      'weightUnit': 'Weight unit',
      'carat': 'Carat',
      'ratti': 'Ratti',
      'invalidGemstoneWeight': 'Enter a weight greater than 0 and not above 100',
      'metal': 'Metal',
      'finger': 'Finger',
      'wearingDay': 'Wearing day',
      'wearingInstructions': 'Traditional wearing instructions',
      'astrologicalReason': 'Astrological reason',
      'evidenceReferences': 'Chart evidence references',
      'evidenceHint': 'One reference per line, or separate with commas',
      'cautions': 'Cautions and verification notes',
      'remedyDecision': 'Astrologer decision',
      'approved': 'Approved',
      'rejected': 'Rejected',
      'saveRemedy': 'Save gemstone remedy',
      'remedySaved': 'Gemstone remedy saved offline',
      'approvalRequiresEvidence': 'At least one chart evidence reference is required for approval',
      'approvalRequiresOutput': 'Verified calculation output is required before approval',
      'remedyTraditionalDisclaimer': 'Traditional astrological guidance only. Verify chart evidence, gemstone authenticity and individual suitability; do not promise medical or guaranteed outcomes.',
      'ephemerisStatus': 'Offline ephemeris status',
      'ephemerisNotConfigured': 'Disabled — the audited offline astronomical backend is not bundled yet.',
      'ephemerisOpenEngine': 'MIT Astronomy Engine backend configured',
      'runKundliAnalysis': 'Run Kundli Analysis',
      'kundliAnalysisRunning': 'Calculating and applying verified rules…',
      'kundliAnalysisReady': 'Kundli calculation and draft analysis saved offline',
      'kundliAnalysisFailed': 'Kundli analysis could not be completed',
      'vedicSystemRequired': 'Select Vedic / Parashari for this consultation to run Kundli analysis.',
      'kundliAnalysis': 'Kundli judgment draft',
      'noKundliAnalysis': 'No Kundli judgment draft has been generated yet.',
      'analysisVersions': 'Immutable versions',
      'professionalReviewRequired': 'Draft only — a professional astrologer must review every finding and remedy candidate.',
      'chartEvidence': 'Chart evidence and rule path',
      'remedyCandidates': 'Behavioural remedy candidates',
      'gemstoneCandidateReview': 'Gemstone candidate & contraindication review',
      'eligible': 'Eligible for professional review',
      'contraindicated': 'Contraindicated for strengthening',
      'insufficientEvidence': 'Insufficient evidence',
      'analysisWarnings': 'Scope and safety warnings',
      'lagnaJudgment': 'Lagna and Lagna-lord judgment',
      'yogaDoshaReview': 'Yoga and Dosha formation review',
      'd1D9Agreement': 'D1–D9 Navamsha agreement',
      'd10CareerReview': 'D10 Dashamsa career review',
      'shadbalaReview': 'Shadbala strength & threshold',
      'ashtakavargaReview': 'Ashtakavarga house support',
      'vimshottariTiming': 'Vimshottari Mahadasha–Antardasha timing',
      'dashaTimeline': 'Vimshottari Dasha timeline',
      'dashaTimelineSummary': 'Open the lifetime Pratyantardasha timeline with chart-specific detailed interpretations and current, past and future filters.',
      'currentDasha': 'Current',
      'pastDasha': 'Past',
      'futureDasha': 'Future',
      'noCurrentDasha': 'No current period exists inside this 120-year cycle.',
      'noDashaPeriods': 'No Dasha period is available in this filter.',
      'pratyantarTimingCaution': 'Pratyantardasha narrows chart activation and provides a detailed review layer. Event confirmation still requires chart promise, the consultation question and transit review.',
      'antardashaTendency': 'Parent Antardasha tendency',
      'pratyantarOwnTendency': 'Pratyantardasha own tendency',
      'pratyantarDetailedInterpretation': 'Detailed Pratyantardasha interpretation',
      'pratyantarTriggerRelation': 'Immediate trigger relation',
      'pratyantarTrigger_reinforcing': 'Reinforcing the broader MD/AD direction',
      'pratyantarTrigger_countertrend': 'Counter-trend against the broader MD/AD direction',
      'pratyantarTrigger_neutral': 'No additional directional trigger',
      'threeLevelDashaSynthesis': 'Three-level Dasha synthesis',
      'score': 'Score',
      'weightedScore': 'Weighted score',
      'dashaWeightFormula': 'Mahadasha ×3 + Antardasha ×2 + Pratyantardasha ×1',
      'activatedLifeAreas': 'Reinforced life areas',
      'contradictoryDashaSignals': 'The three lords contain opposite signals, so the combined result remains Mixed.',
      'pratyantarNoJudgment': 'This legacy period has no linked Antardasha judgment. Professional review is required.',
      'reviewRequired': 'Professional review',
      'twelveHouseJudgment': 'Twelve-house condition',
      'detailedLifeAreaJudgment': 'Detailed life-area judgment',
      'functionalPlanetRoles': 'Functional planet tendencies',
      'houseOccupancy': 'Planets occupying houses',
      'parashariAspects': 'Parashari full sign aspects',
      'planetConditions': 'Combustion and retrograde review',
      'aspectSynthesis': 'Multi-aspect synthesis',
      'conjunctions': 'Same-sign conjunctions',
      'friendshipAndMoolatrikona': 'Planetary friendship and Moolatrikona',
      'planetaryWarReview': 'Planetary-war review',
      'overall': 'Overall',
      'self': 'Self and vitality',
      'family': 'Family and speech',
      'communication': 'Communication and courage',
      'siblings': 'Siblings',
      'obstacles': 'Obstacles, debt and conflict',
      'longevity': 'Longevity and transformation',
      'fortune': 'Fortune and dharma',
      'gains': 'Gains and networks',
      'expenses': 'Expenses and withdrawal',
      'spirituality': 'Spirituality',
      'supportive': 'Supportive',
      'challenging': 'Challenging',
      'mixed': 'Mixed',
      'low': 'Low confidence',
      'medium': 'Medium confidence',
      'high': 'High confidence',
      'generateProfessionalReport': 'Generate professional report',
      'professionalReports': 'Professional consultation reports',
      'professionalReportPreview': 'Professional report preview',
      'professionalReportCreated': 'Professional report snapshot created',
      'professionalReportReady': 'Professional report generated and saved offline',
      'professionalReportFailed': 'Professional report could not be generated',
      'noProfessionalReports': 'No professional report snapshot has been generated yet.',
      'reportHash': 'Report SHA-256',
      'reportAsOf': 'Report as of',
      'reportSafetyWarnings': 'Report safety and scope warnings',
      'exportReportPdf': 'Export / share PDF',
      'exportReportDocx': 'Export / share DOCX',
      'reportExporting': 'Generating export file…',
      'reportExportReady': 'Report export generated offline',
      'reportExportFailed': 'Report export could not be generated',
      'reportExportHash': 'Export SHA-256',
      'reportExportNote': 'PDF/DOCX files are generated from this immutable report snapshot. The source report hash remains embedded in the exported document.',
      'reportApprovalTitle': 'Professional approval and sign-off',
      'reportNotApproved': 'Not yet approved for client delivery',
      'reportApproved': 'Approved and locked',
      'approveReport': 'Review and approve report',
      'approvalImmutableNote': 'Approval is permanent for this report snapshot. To change the professional opinion, create a new report snapshot.',
      'approvalElectronicDisclosure': 'This is an in-app practitioner electronic sign-off, not a certificate-backed cryptographic/digital signature.',
      'practitionerName': 'Practitioner name',
      'practitionerDesignation': 'Designation / professional identity',
      'credentialReference': 'Credential / registration reference (optional)',
      'approvalDecision': 'Approval decision',
      'approvedForClientDelivery': 'Approved for client delivery',
      'approvedWithReservations': 'Approved with reservations',
      'approvalNote': 'Approval note',
      'approvalNoteRequired': 'A note is required when approving with reservations.',
      'approvalAttestation': 'I reviewed this immutable report snapshot and understand this action cannot be edited or undone.',
      'approvalAttestationRequired': 'Confirm the approval acknowledgement before signing.',
      'approvalSave': 'Approve and lock this report',
      'approvalSaving': 'Saving immutable approval…',
      'approvalSaved': 'Professional approval saved and locked',
      'approvalFailed': 'Professional approval could not be saved',
      'approvedAt': 'Approved at (UTC)',
      'approvalHash': 'Approval SHA-256',
      'signedReportHash': 'Signed-report SHA-256',
      'approvalContract': 'Approval contract',
      'signedReportVerificationQr': 'Signed report verification QR',
      'verifySignedReport': 'Verify signed report',
      'copyVerificationPayload': 'Copy verification payload',
      'verificationPayloadCopied': 'Verification payload copied',
      'signedReportVerifierTitle': 'Signed report verifier',
      'signedReportVerifierIntro': 'Paste an ASTRO LOGIC signed-report verification payload, or open this screen from a locally signed report. Verification runs offline against immutable local records.',
      'verificationPayload': 'Verification payload',
      'verificationPayloadHint': 'Paste the compact JSON payload carried by the report QR.',
      'pasteAndVerify': 'Paste and verify',
      'verificationScopeDisclosure': 'A structurally valid QR/payload is not by itself proof of practitioner identity or authenticity. Full verification requires a matching immutable report and approval record in this ASTRO LOGIC database.',
      'verificationContract': 'Verification contract',
      'verificationVerifiedLocal': 'Verified against local immutable record',
      'verificationNoLocalRecord': 'Valid payload, but no matching local record',
      'verificationMismatchDetected': 'Mismatch or tamper detected',
      'verificationInvalidPayload': 'Invalid or unsupported verification payload',
      'verificationPayloadParseFailed': 'The payload could not be parsed under the supported verification contract.',
      'verificationPayloadHashMismatch': 'The signed-report hash does not match the report/approval hashes carried by this payload.',
      'verificationPayloadInternallyConsistent': 'The payload is internally consistent under the supported hash contract.',
      'verificationAuthenticityNotEstablished': 'No matching local immutable record was found; practitioner authenticity is not established.',
      'verificationReportIdentityMismatch': 'The local report identity does not match the payload.',
      'verificationStoredReportHashMismatch': 'The stored report content no longer matches its persisted report hash.',
      'verificationReportHashVerified': 'The immutable report content recomputes to the stored report hash.',
      'verificationLocalApprovalMissing': 'The matching local report has no corresponding immutable approval record.',
      'verificationApprovalContractInvalid': 'The stored approval contract metadata is invalid or unsupported.',
      'verificationApprovalIdentityMismatch': 'The local approval metadata does not match the payload.',
      'verificationStoredApprovalHashMismatch': 'The stored approval metadata no longer matches its approval hash.',
      'verificationApprovalHashVerified': 'The immutable approval metadata recomputes to the stored approval hash.',
      'verificationStoredSignedHashMismatch': 'The local signed-report hash does not recompute from the report and approval hashes.',
      'verificationSignedHashVerified': 'The signed-report hash recomputes correctly from the report and approval hashes.',
      'verificationLocalImmutableRecordMatched': 'Report and approval records match this payload inside the local database.',
      'reportStatus_available': 'Available',
      'reportStatus_limited': 'Limited / curated',
      'reportStatus_unavailable': 'Unavailable',
      'confidence': 'Confidence',
    },
    'bn': {
      'welcome': 'পেশাদার জ্যোতিষ কর্মক্ষেত্র',
      'newConsultation': 'নতুন পরামর্শ',
      'clients': 'ক্লায়েন্ট',
      'vedic': 'বৈদিক / পরাশরী',
      'kp': 'কেপি জ্যোতিষ',
      'kpWorkspace': 'KP Native Chart Workspace',
      'kpFoundationTitle': 'Governed KP Native Chart v4',
      'kpPointClassifier': 'Sign / star / sub classifier',
      'kpSiderealLongitude': 'Sidereal longitude (0°–<360°)',
      'kpLongitudeHelper': 'স্বতন্ত্র Star/Sub review-এর জন্য আগে থেকে sidereal করা longitude দিন।',
      'kpClassifyPoint': 'Sign / star / sub নির্ণয় করুন',
      'kpRulingPlanets': 'Ruling planets — review profile',
      'kpAscendantLongitude': 'Ascendant sidereal longitude',
      'kpMoonLongitude': 'Moon sidereal longitude',
      'kpWeekday': 'Judgment moment-এর weekday',
      'kpBuildRulingPlanets': 'Ruling-planet evidence তৈরি করুন',
      'kpCuspFramework': '12-cusp classification framework',
      'kpCuspLongitudes': '12টি sidereal cusp longitude',
      'kpCuspHelper': 'প্রতি লাইনে একটি বা comma-separated দিন। Native Placidus casting-এর পাশাপাশি manual cross-check হিসেবে এটি থাকবে।',
      'kpClassifyCusps': 'Supplied cusps classify করুন',
      'kpInvalidLongitude': '0 inclusive থেকে 360 exclusive-এর মধ্যে valid sidereal longitude দিন।',
      'kpInvalidCusps': 'ঠিক 12টি valid sidereal cusp longitude দিন।',
      'kpSourceSafetyNote': 'Native scope: governed KP ayanamsha, native Placidus cusps, planet/cusp Star/Sub, house occupancy/ownership, four-level significators, Marriage/Children-এর source-bounded Vimshottari DBA timing, Transit/Ruling-Planet confirmation এবং আলাদা query-time Horary RP corroboration। Horary RP corroboration natal DBA reuse করে না বা exact future date তৈরি করে না।',
      'runKpNativeChart': 'Immutable KP native chart তৈরি করুন',
      'kpNativeRunning': 'KP native chart তৈরি হচ্ছে…',
      'kpNativeReady': 'KP native chart snapshot সংরক্ষিত হয়েছে',
      'kpNativeFailed': 'KP native chart তৈরি করা যায়নি।',
      'kpSystemRequired': 'Governed KP chart সংরক্ষণের জন্য consultation-এ KP নির্বাচন করুন।',
      'kpNativeCasting': 'Native KP chart casting',
      'kpUtcDateTime': 'UTC date/time (ISO 8601)',
      'kpLatitude': 'Latitude',
      'kpLongitude': 'Longitude',
      'kpCastNativeChart': 'Native KP chart তৈরি করুন',
      'kpAyanamsha': 'Krishnamurti ayanamsha',
      'kpNativeChartFailed': 'Native KP chart casting ব্যর্থ হয়েছে।',
      'kpPlacidusNoFallback': 'Unsupported polar geometry-তে Placidus reject হবে; Porphyry fallback ব্যবহার করা হবে না।',
      'kpAdvancedSignificators': 'Advanced four-level significators',
      'kpEventReviewTopic': 'KP event-promise review',
      'kpEventMarriage': 'বিবাহ — 7th cusp / 2-7-11',
      'kpEventChildren': 'সন্তান — 5th cusp / 2-5-11',
      'kpReviewEventEvidence': 'Cusp sub-lord evidence review করুন',
      'kpEventState': 'KP review state',
      'kpDashaTiming': 'KP বিমশোত্তরী দশা / ভুক্তি / অন্তর timing',
      'kpTimingGate': 'Timing gate',
      'kpSupportiveWindows': 'Supportive window',
      'kpConflictingWindows': 'Conflicting window',
      'kpCurrentDba': 'বর্তমান DBA',
      'kpNextSupportiveWindows': 'পরবর্তী supportive window',
      'kpNoSupportiveTiming': 'বর্তমান chart-promise gate অনুযায়ী কোনো supportive window promote করা হচ্ছে না।',
      'kpTimingSeparationNote': 'DBA timing base layer হিসেবেই থাকবে। Transit এবং Ruling-Planet confirmation আলাদা করে evaluate হবে এবং DBA state rewrite করবে না।',
      'kpTimingConfirmation': 'KP Transit + Ruling-Planet confirmation',
      'kpConfirmationState': 'Confirmation state',
      'kpConfidenceCeiling': 'Confidence ceiling',
      'kpRpOverlap': 'Fruitful standard RP overlap',
      'kpConfirmationSafetyNote': 'Transit/RP confirmation review ceiling সর্বোচ্চ Moderate পর্যন্ত তুলতে পারে। এটি event বা exact date নিশ্চিত করে না।',
      'kpTimingConfirmationFailed': 'KP transit/Ruling-Planet confirmation তৈরি করা যায়নি।',
      'kpHoraryTitle': 'KP Horary / প্রশ্ন — 1–249',
      'kpHoraryIntro': 'একটি স্পষ্ট প্রশ্ন, স্বতঃস্ফূর্ত 1–249 নম্বর এবং প্রশ্নের সঠিক সময়/স্থান ব্যবহার করুন। জন্মতথ্য ব্যবহার হবে না।',
      'kpHoraryNumber': 'Horary নম্বর',
      'kpHoraryTopic': 'প্রশ্নের evidence profile',
      'kpHoraryGeneral': 'সাধারণ — automatic event judgment নয়',
      'kpHoraryQuestion': 'একটি Horary প্রশ্ন',
      'kpHoraryQuestionHelper': 'প্রতি immutable snapshot-এ একটি নির্দিষ্ট প্রশ্ন রাখুন।',
      'kpHoraryMomentLocationNote': 'উপরের UTC/latitude/longitude প্রশ্নের সময় ও স্থান। গ্রহগুলো সেই সময়ের; Horary নম্বর Ascendant নির্ধারণ করবে।',
      'kpHoraryCastSave': 'Horary chart তৈরি করে immutable snapshot সংরক্ষণ করুন',
      'kpHoraryAscendant': 'Horary Ascendant',
      'kpHoraryCuspError': 'Cusp-1 bind error',
      'kpHoraryCuspEvidence': 'প্রশ্ন-cusp evidence',
      'kpHoraryRpTiming': 'Query-time Ruling-Planet corroboration',
      'kpHoraryRpState': 'Horary timing corroboration',
      'kpHoraryPrimaryRpOverlap': 'Primary cusp sub-lord standard RP set-এ আছে',
      'kpHoraryYes': 'হ্যাঁ',
      'kpHoraryNo': 'না',
      'kpHoraryFruitfulRp': 'Fruitful standard RP planet',
      'kpHoraryMixedRp': 'Mixed standard RP planet',
      'kpHoraryDetrimentalRp': 'Detrimental-only standard RP planet',
      'kpHoraryConfidence': 'Horary confidence ceiling',
      'kpHoraryRpSafety': 'এটি শুধু query-moment Ruling-Planet corroboration। Natal DBA, জন্মতথ্য ও future transit scan ব্যবহার করা হয় না; exact event date তৈরি করা হয় না।',
      'kpHoraryGeneralNoAutoJudgment': 'General Horary-তে 12 cusp, planet, significator ও Ruling Planet practitioner review-এর জন্য থাকবে; generic Promise/Denial formula বানানো হবে না।',
      'kpHorarySnapshot': 'সংরক্ষিত snapshot ID',
      'kpHorarySavedTotal': 'সংরক্ষিত Horary snapshot',
      'kpHorarySafetyNote': 'Placidus cusp geometry solve করার technical UTC event time নয়। Horary output practitioner-review material; নিশ্চিত yes/no ফল নয়।',
      'kpHoraryFailed': 'KP Horary chart তৈরি বা সংরক্ষণ করা যায়নি।',

      'weekday1': 'সোমবার',
      'weekday2': 'মঙ্গলবার',
      'weekday3': 'বুধবার',
      'weekday4': 'বৃহস্পতিবার',
      'weekday5': 'শুক্রবার',
      'weekday6': 'শনিবার',
      'weekday7': 'রবিবার',
      'western': 'ওয়েস্টার্ন জ্যোতিষ',
      'westernWorkspace': 'ওয়েস্টার্ন নেটাল চার্ট ওয়ার্কস্পেস',
      'westernFoundationTitle': 'Western Astrology Modern Evidence v2',
      'westernFoundationDisclosure': 'পেশাদার পর্যালোচনার জন্য Tropical chart evidence। Rulership, aspect, modern-planet ও pattern profile output-এর সঙ্গে সংরক্ষিত থাকে; automatic event prediction বা cross-system confidence uplift তৈরি হয় না।',
      'westernUtcDateTime': 'UTC তারিখ/সময় (ISO 8601)',
      'westernLatitude': 'অক্ষাংশ',
      'westernLongitude': 'দ্রাঘিমাংশ',
      'westernHouseSystemLabel': 'House system',
      'westernNodeModeLabel': 'Lunar node mode',
      'westernCastChart': 'Western natal chart তৈরি করুন',
      'westernChartRunning': 'Western natal chart তৈরি হচ্ছে…',
      'westernChartReady': 'Western natal chart snapshot সংরক্ষিত হয়েছে',
      'westernChartFailed': 'Western natal chart তৈরি করা যায়নি।',
      'westernSystemRequired': 'Governed Western chart সংরক্ষণ করতে এই consultation-এ Western Astrology নির্বাচন করুন।',
      'westernAscMc': 'Ascendant / Midheaven',
      'westernPlanetsHouses': 'Tropical planet ও house',
      'westernMajorAspects': 'Major aspects',
      'westernNoMajorAspects': 'Governed major-aspect orb profile-এর মধ্যে কোনো aspect নেই।',
      'westernRulershipProfileLabel': 'Rulership profile',
      'westernRulership_traditional': 'Traditional rulership',
      'westernRulership_modern': 'Modern rulership',
      'westernAspectProfileLabel': 'Aspect profile',
      'westernAspectProfile_majorOnly': 'শুধু Major',
      'westernAspectProfile_majorAndMinor': 'Major + governed Minor',
      'westernModernPlanets': 'Modern planets — native astronomical positions',
      'westernModernPlanetsDisabled': 'এই chart-এ modern-planet output বন্ধ আছে।',
      'westernPlanetColumn': 'Planet',
      'westernLongitudeColumn': 'Longitude',
      'westernLatitudeColumn': 'Latitude',
      'westernHouseColumn': 'House',
      'westernAspects': 'Aspect evidence table',
      'westernNoAspects': 'Selected governed orb profile-এর মধ্যে কোনো aspect নেই।',
      'westernAspectPairColumn': 'Planets',
      'westernAspectColumn': 'Aspect',
      'westernOrbColumn': 'Orb / limit',
      'westernMotionColumn': 'Motion',
      'westernAspectPatterns': 'Aspect pattern evidence',
      'westernNoAspectPatterns': 'কোনো governed aspect pattern নেই।',
      'westernPatternEvidenceNote': 'Pattern-এর component planet, aspect ও orb evidence সংরক্ষিত থাকে। Loose geometry থেকে pattern বানানো হয় না এবং কোনো life-event prediction তৈরি হয় না।',
      'westernRulerships': 'Sign rulership evidence',
      'westernDignities': 'Traditional essential dignity evidence',
      'westernNoDignity': 'Domicile/exaltation/detriment/fall condition নেই',
      'westernDignitySeparationNote': 'Modern sign ruler authoritative traditional domicile/exaltation/detriment/fall evidence পরিবর্তন করে না।',
      'westernAspectOrbNote': 'Aspect orb একটি versioned ASTRO LOGIC operating profile; এটি universal historical standard হিসেবে দাবি করা হয় না।',
      'westernPlacidusNoFallback': 'Unsupported polar geometry-তে Placidus reject হবে; Whole Sign বা Equal house system স্পষ্টভাবে নির্বাচন করতে হবে, silent fallback হবে না।',
      'westernScopeNote': 'v2-তে native Uranus, Neptune ও Pluto, explicit rulership profile, optional minor aspects এবং deterministic pattern evidence যোগ হয়েছে। Traditional essential dignity সাতটি traditional planet-এর মধ্যেই সীমাবদ্ধ; triplicity, terms ও faces এই profile-এর বাইরে।',
      'uranus': 'ইউরেনাস',
      'neptune': 'নেপচুন',
      'pluto': 'প্লুটো',
      'semisextile': 'সেমিসেক্সটাইল',
      'semisquare': 'সেমিস্কোয়ার',
      'quintile': 'কুইন্টাইল',
      'sesquiquadrate': 'সেস্কুইকোয়াড্রেট',
      'quincunx': 'কুইনকাঙ্কস / ইনকনজাঙ্ক্ট',
      'grandTrine': 'গ্র্যান্ড ট্রাইন',
      'tSquare': 'টি-স্কোয়ার',
      'grandCross': 'গ্র্যান্ড ক্রস',
      'stellium': 'স্টেলিয়াম',
      'yod': 'ইয়ড',
      'kite': 'কাইট',
      'northNode': 'উত্তর নোড',
      'southNode': 'দক্ষিণ নোড',
      'conjunction': 'Conjunction',
      'sextile': 'Sextile',
      'square': 'Square',
      'trine': 'Trine',
      'opposition': 'Opposition',
      'applying': 'Applying',
      'separating': 'Separating',
      'domicile': 'Domicile',
      'exaltation': 'Exaltation',
      'detriment': 'Detriment',
      'fall': 'Fall',
      'numerology': 'সংখ্যাতত্ত্ব',
      'numerologyWorkspace': 'সংখ্যাতত্ত্ব পরামর্শ কর্মক্ষেত্র',
      'numerologyIntro': 'অফলাইন পেশাদার-পর্যালোচনা প্রোফাইলের জন্য সঠিক ইংরেজি বানান ও জন্মতারিখ দিন।',
      'latinNameForCalculation': 'নামের সঠিক ইংরেজি / ল্যাটিন বানান',
      'exactSpellingNote': 'অ্যাপ নিজে এই বানান transliterate বা পরিবর্তন করবে না।',
      'alternateSpellings': 'তুলনার জন্য বিকল্প ইংরেজি বানান',
      'alternateSpellingsHint': 'প্রতি লাইনে একটি English / Latin spelling দিন (সর্বোচ্চ ৮টি)। Engine তুলনা করবে, rank করবে না।',
      'nameCandidateComparison': 'বিকল্প নামের arithmetic তুলনা',
      'professionalNameFocus': 'Professional discussion focus',
      'professionalNameFocusNone': 'কোনো candidate নির্বাচিত নয়',
      'professionalNameFocusAction': 'Professional discussion-এর জন্য নির্বাচন করুন',
      'professionalNameFocusClear': 'Professional focus সরান',
      'nameCandidateSafety': 'শুধু arithmetic comparison — best/lucky-name ranking বা automatic name-change recommendation নেই।',
      'numerologySpellingInvalid': 'শুধু ইংরেজি অক্ষর, space, full stop, hyphen বা apostrophe ব্যবহার করুন।',
      'selectBirthDate': 'জন্মতারিখ নির্বাচন করুন',
      'personalYearTarget': 'পার্সোনাল ইয়ার নির্বাচন',
      'calculateNumerology': 'সংখ্যাতত্ত্ব গণনা ও বিচার করুন',
      'numerologyCalculationFailed': 'সংখ্যাতত্ত্ব গণনা সম্পন্ন করা যায়নি।',
      'calculationBreakdown': 'যাচাইকৃত গণনার বিবরণ',
      'driverNumber': 'ড্রাইভার / জন্মসংখ্যা',
      'lifePathNumber': 'লাইফ পাথ',
      'maturityNumber': 'ম্যাচিউরিটি synthesis',
      'personalYearNumber': 'পার্সোনাল ইয়ার',
      'pythagoreanExpression': 'পাইথাগোরিয়ান এক্সপ্রেশন',
      'soulUrgeNumber': 'সোল আর্জ',
      'personalityNumber': 'পার্সোনালিটি',
      'chaldeanNameNumber': 'চ্যালডিয়ান নামসংখ্যা',
      'calculationEvidence': 'গণনার প্রমাণ ও rule ID',
      'strengthsChallenges': 'শক্তি ও পর্যালোচনার প্রবণতা',
      'personalYearWindow': 'তিন বছরের পার্সোনাল ইয়ার context',
      'vedicCrossCheck': 'সুরক্ষিত বৈদিক cross-check',
      'numerologyPredictionConfidence': 'Prediction confidence policy',
      'numerologyRemedyReview': 'আচরণগত সমাধান প্রার্থী',
      'numerologyWarnings': 'সংখ্যাতত্ত্বের পরিধি ও নিরাপত্তা সতর্কতা',
      'runNumerologyAnalysis': 'সংখ্যাতত্ত্ব বিচার খুলুন',
      'numerologySystemRequired': 'Governed profile সংরক্ষণ করতে এই পরামর্শে সংখ্যাতত্ত্ব নির্বাচন করুন।',
      'saveNumerologySnapshot': 'অপরিবর্তনীয় সংখ্যাতত্ত্ব snapshot সংরক্ষণ করুন',
      'numerologySnapshotSaving': 'অপরিবর্তনীয় snapshot সংরক্ষণ হচ্ছে…',
      'numerologySnapshotSaved': 'সংখ্যাতত্ত্ব snapshot অফলাইনে সংরক্ষিত হয়েছে',
      'savedNumerologySnapshots': 'সংরক্ষিত সংখ্যাতত্ত্ব snapshot',
      'numerologyImmutableNote': 'সংরক্ষিত version স্থায়ী, hash-সুরক্ষিত এবং edit বা delete করা যায় না।',
      'noNumerologySnapshots': 'এই পরামর্শে কোনো সংখ্যাতত্ত্ব snapshot সংরক্ষিত হয়নি।',
      'snapshotHash': 'Snapshot SHA-256',
      'numerologySnapshotCreated': 'সংখ্যাতত্ত্ব snapshot তৈরি হয়েছে',
      'vastu': 'বাস্তু',
      'palmistry': 'হস্তরেখা',
      'gemstoneRemedies': 'গ্রহরত্ন সমাধান',
      'reports': 'রিপোর্ট',
      'practice': 'প্র্যাকটিস',
      'settings': 'গণনার সেটিংস',
      'offline': 'অফলাইন ও ব্যক্তিগত',
      'comingSoon': 'মডিউলের ভিত্তি প্রস্তুত',
      'addClient': 'ক্লায়েন্ট যোগ করুন',
      'searchClients': 'ক্লায়েন্ট খুঁজুন',
      'noClients': 'এখনও কোনো ক্লায়েন্ট নথিভুক্ত নেই',
      'clientDetails': 'ক্লায়েন্টের তথ্য',
      'fullName': 'সম্পূর্ণ নাম',
      'mobile': 'মোবাইল নম্বর',
      'email': 'ইমেল (ঐচ্ছিক)',
      'gender': 'লিঙ্গ',
      'male': 'পুরুষ',
      'female': 'মহিলা',
      'other': 'অন্যান্য / বলতে অনিচ্ছুক',
      'notes': 'পেশাগত নোট (ঐচ্ছিক)',
      'birthDetails': 'জন্মের তথ্য',
      'birthLabel': 'রেকর্ডের নাম',
      'birthDate': 'জন্মতারিখ',
      'birthTime': 'জন্মসময়',
      'birthPlace': 'জন্মস্থান',
      'latitude': 'অক্ষাংশ',
      'longitude': 'দ্রাঘিমাংশ',
      'utcOffset': 'জন্মসময়ের UTC পার্থক্য',
      'timeConfidence': 'জন্মসময়ের নির্ভরযোগ্যতা',
      'exact': 'নির্ভুল',
      'recorded': 'নথিভুক্ত',
      'approximate': 'আনুমানিক',
      'unknown': 'অজানা',
      'sourceNote': 'জন্মসময়ের উৎস / মন্তব্য',
      'save': 'ক্লায়েন্ট সংরক্ষণ করুন',
      'required': 'এই তথ্যটি আবশ্যক',
      'invalidNumber': 'সঠিক সংখ্যা লিখুন',
      'invalidLatitude': 'অক্ষাংশ -90 থেকে 90-এর মধ্যে হতে হবে',
      'invalidLongitude': 'দ্রাঘিমাংশ -180 থেকে 180-এর মধ্যে হতে হবে',
      'futureDate': 'জন্মতারিখ ভবিষ্যতের হতে পারে না',
      'saved': 'ক্লায়েন্টের তথ্য অফলাইনে সংরক্ষিত হয়েছে',
      'birthRecord': 'প্রাথমিক জন্ম রেকর্ড',
      'databaseError': 'সংরক্ষণ করা যায়নি। আবার চেষ্টা করুন।',
      'edit': 'সম্পাদনা',
      'clientProfile': 'ক্লায়েন্ট প্রোফাইল',
      'birthRecords': 'জন্ম রেকর্ডসমূহ',
      'addBirthRecord': 'জন্ম রেকর্ড যোগ করুন',
      'editBirthRecord': 'জন্ম রেকর্ড সম্পাদনা করুন',
      'localTime': 'স্থানীয় জন্মসময়',
      'utcTime': 'হিসাব করা UTC',
      'coordinates': 'স্থানাঙ্ক',
      'updated': 'পরিবর্তন অফলাইনে সংরক্ষিত হয়েছে',
      'ayanamsha': 'ডিফল্ট অয়নাংশ',
      'lahiri': 'লাহিড়ী',
      'raman': 'রামন',
      'krishnamurti': 'কৃষ্ণমূর্তি',
      'vedicChartStyle': 'বৈদিক চার্টের ধরন',
      'northIndian': 'উত্তর ভারতীয়',
      'southIndian': 'দক্ষিণ ভারতীয়',
      'eastIndian': 'পূর্ব ভারতীয়',
      'westernHouseSystem': 'ওয়েস্টার্ন হাউস পদ্ধতি',
      'placidus': 'প্ল্যাসিডাস',
      'wholeSign': 'হোল সাইন',
      'equal': 'ইকুয়াল হাউস',
      'lunarNodeMode': 'রাহু/কেতু গণনা',
      'trueNode': 'ট্রু নোড',
      'meanNode': 'মিন নোড',
      'settingsNote': 'ভবিষ্যতের প্রতিটি calculation snapshot-এর সঙ্গে এই default সেটিংস সংরক্ষিত থাকবে।',
      'saveSettings': 'গণনার সেটিংস সংরক্ষণ করুন',
      'refresh': 'রিফ্রেশ',
      'importLedgerTitle': 'ব্যাকআপ ইমপোর্ট ব্যাচ লেজার',
      'importLedgerIntro': 'Governed backup merge-এর durable local history। প্রতিটি committed batch source manifest-কে source/local ID mapping ও exportable receipt hash-এর সঙ্গে bind করে। Failed বা interrupted attempt-এর diagnostics থাকবে, কিন্তু partial imported row থাকবে না।',
      'importLedgerEmpty': 'এখনও কোনো governed backup merge batch record হয়নি।',
      'importBatch': 'ইমপোর্ট ব্যাচ',
      'importBatchStatus': 'স্ট্যাটাস',
      'importBatchStarted': 'শুরু UTC',
      'importBatchCompleted': 'সম্পন্ন UTC',
      'importBatchSource': 'Source app / engine',
      'importBatchSchema': 'Source schema',
      'importBatchMappings': 'Source → local mapping',
      'importBatchReceiptHash': 'Merge receipt SHA-256',
      'importBatchDiagnostics': 'Recovery diagnostics',
      'importBatchCommitted': 'Committed',
      'importBatchFailed': 'Failed / rollback হয়েছে',
      'importBatchStartedStatus': 'অসম্পূর্ণ / started',
      'viewMappings': 'ID mapping দেখুন',
      'exportMergeReceipt': 'Merge receipt export করুন',
      'mergeReceiptFailed': 'Merge receipt export করা যায়নি অথবা ledger hash verify হয়নি।',
      'noImportMappings': 'এই batch-এর জন্য কোনো committed source/local mapping নেই।',
      'mappingSourceId': 'Source ID',
      'mappingLocalId': 'Local ID',
      'mappingResolution': 'Resolution',
      'mapping_inserted': 'Source ID-তেই insert হয়েছে',
      'mapping_equivalent': 'Equivalent local row reuse হয়েছে',
      'mapping_remapped': 'Primary key remap হয়েছে',
      'mappingSourceHash': 'Source-row SHA-256',
      'mappingLocalHash': 'Local-row SHA-256',
      'backupRestore': 'এনক্রিপ্টেড ব্যাকআপ ও রিস্টোর',
      'backupRestoreTitle': 'এনক্রিপ্টেড ব্যাকআপ ও রিস্টোর',
      'encryptedBackupTitle': 'পাসওয়ার্ড-সুরক্ষিত এনক্রিপ্টেড ব্যাকআপ',
      'encryptedBackupIntro': 'ক্লায়েন্ট, জন্মতথ্য, consultation, settings, audit history এবং সব governed calculation, analysis, report ও approval record-এর portable offline backup তৈরি করুন।',
      'encryptedBackupCryptoDisclosure': 'Backup v1-এ Argon2id password key derivation এবং AES-256-GCM authenticated encryption ব্যবহৃত হয়। Password backup বা database-এ সংরক্ষণ করা হয় না।',
      'createEncryptedBackup': 'এনক্রিপ্টেড ব্যাকআপ তৈরি করুন',
      'restoreEncryptedBackup': 'এনক্রিপ্টেড ব্যাকআপ রিস্টোর করুন',
      'restoreEmptyWorkspaceOnly': 'Encrypted restore, governed non-empty merge, conflict planning এবং durable import-batch ledger।',
      'restoreNoMergeWarning': 'Existing record overwrite করা হবে না। Governed merge equivalent row reuse করতে পারে এবং primary-key collision deterministic ভাবে remap করে original immutable identity অক্ষুণ্ণ রাখে।',
      'selectBackupAndRestore': '.albackup ফাইল বেছে রিস্টোর করুন',
      'restorePreviewTitle': 'রিস্টোর প্রিভিউ ও কনফ্লিক্ট প্ল্যানার',
      'restorePreviewIntro': 'Database-এ কোনো পরিবর্তন করার আগে backup decrypt ও validate করুন। প্রথমে source version, schema, table count, integrity এবং same-ID conflict দেখানো হবে।',
      'selectBackupAndPreview': '.albackup ফাইল বেছে প্রিভিউ করুন',
      'restorePreviewedBackup': 'এই verified backup রিস্টোর করুন',
      'restoreBlockedByPlanner': 'Preview planner এই backup-কে empty restore বা governed merge—কোনোটির জন্যই নিরাপদ বলে অনুমোদন করেনি।',
      'restorePreviewCompleted': 'Database পরিবর্তন না করেই backup decrypt ও preview সম্পন্ন হয়েছে।',
      'restorePreviewFailed': 'Backup preview সম্পন্ন করা যায়নি।',
      'restorePreviewVerified': 'Pre-restore verification ফলাফল',
      'previewSourceApp': 'Source app version',
      'previewBackupEngine': 'Backup engine version',
      'previewSourceSchema': 'Source database schema',
      'previewBackupCreated': 'Backup তৈরির সময় (UTC)',
      'previewManifestIntegrity': 'Manifest integrity',
      'previewSnapshotIntegrity': 'Governed snapshot integrity',
      'previewIncomingRows': 'Incoming protected row',
      'previewLocalSensitiveRows': 'Existing governed local row',
      'previewDatabaseMutation': 'Preview-র সময় database mutation',
      'previewMergeExecution': 'Governed merge/remap',
      'previewEligible': 'Eligible: বর্তমান schema + খালি workspace। Password আবার দিয়ে restore করা যাবে।',
      'previewBlockedNonEmpty': 'Blocked: বর্তমান workspace-এ এই backup নিরাপদভাবে merge করা যাচ্ছে না।',
      'previewRequiresMigration': 'Migration দরকার: backup schema ও বর্তমান app schema আলাদা। Restore disabled।',
      'previewUnsupported': 'এই app version-এর জন্য backup unsupported।',
      'previewTableCounts': 'Backup table অনুযায়ী row count',
      'previewConflictPlan': 'Table অনুযায়ী ID conflict plan',
      'previewIncoming': 'Incoming',
      'previewLocal': 'Local',
      'previewNewIds': 'নতুন ID',
      'previewEquivalentIds': 'Equivalent ID',
      'previewConflictingIds': 'Unresolved conflict',
      'previewRemappedIds': 'Remapped ID',
      'previewMergeEligible': 'Eligible: local record overwrite না করে governed merge transactionally চালানো যাবে।',
      'mergePreviewedBackup': 'এই verified backup merge করুন',
      'mergeConfirmTitle': 'এই workspace-এ governed merge করবেন?',
      'mergeConfirmMessage': 'Equivalent row reuse হবে, primary-key collision deterministic ভাবে remap হবে এবং original source ID/hash অক্ষুণ্ণ থাকবে। কোনো validation বা insert fail হলে পুরো transaction rollback হবে।',
      'mergeCompleted': 'Governed backup merge ও verification সম্পন্ন হয়েছে।',
      'mergeFailed': 'Governed backup merge সম্পন্ন করা যায়নি। কোনো partial merge রাখা হয়নি।',
      'mergeVerified': 'Integrity verification-এর পর governed merge সম্পন্ন হয়েছে',
      'mergeInsertedRows': 'Insert করা row',
      'mergeEquivalentSkipped': 'Reuse করা equivalent row',
      'mergeRemappedRows': 'Remap করা row',
      'mergeRollbackPolicy': 'Rollback policy',
      'enabled': 'Enabled',
      'verified': 'Verified',
      'notVerified': 'Not verified',
      'requiresMigrationReview': 'চালানো হয়নি — schema migration review দরকার',
      'nonePerformed': 'কোনো পরিবর্তন নয়',
      'disabled': 'Disabled',
      'backupRestoreWorking': 'ডেটা encrypt, validate বা restore করা হচ্ছে…',
      'backupPasswordCreateTitle': 'ব্যাকআপ পাসওয়ার্ড তৈরি করুন',
      'backupPasswordEnterTitle': 'ব্যাকআপ পাসওয়ার্ড দিন',
      'backupPassword': 'ব্যাকআপ পাসওয়ার্ড',
      'confirmBackupPassword': 'ব্যাকআপ পাসওয়ার্ড আবার দিন',
      'backupPasswordRule': 'কমপক্ষে ১২টি character ব্যবহার করুন। দীর্ঘ এবং আলাদা passphrase ব্যবহার করা ভালো।',
      'backupPasswordTooShort': 'Password কমপক্ষে ১২টি character হতে হবে।',
      'backupPasswordMismatch': 'দুইটি password মিলছে না।',
      'passwordNotStoredWarning': 'ASTRO LOGIC এই password সংরক্ষণ বা recover করে না। Password হারালে backup decrypt করা যাবে না।',
      'backupCreated': 'Encrypted backup তৈরি ও integrity manifest seal হয়েছে',
      'backupCreateFailed': 'Encrypted backup তৈরি করা যায়নি।',
      'backupShareNote': 'ASTRO LOGIC encrypted backup। Password backup file থেকে আলাদা জায়গায় রাখুন।',
      'backupManifestHash': 'Manifest SHA-256',
      'backupFileHash': 'Encrypted file SHA-256',
      'backupRecordCount': 'Protected rows',
      'backupFileReadFailed': 'নির্বাচিত backup file পড়া যায়নি।',
      'backupFileTooLarge': 'নির্বাচিত backup-টি v1-এর 128 MiB সীমার বেশি।',
      'restoreConfirmTitle': 'Protected data রিস্টোর করবেন?',
      'restoreConfirmMessage': 'শুধু workspace খালি থাকলে restore হবে। সঠিক password দিয়ে file authenticate হতে হবে এবং সব manifest/hash/foreign-key check pass করতে হবে।',
      'restoreCompleted': 'Encrypted backup offline-এ restore ও verify হয়েছে।',
      'restoreFailed': 'Encrypted backup restore করা যায়নি।',
      'restoreVerified': 'Integrity verification-এর পর restore সম্পন্ন হয়েছে',
      'importedAuditEvents': 'Import করা audit events',
      'cancel': 'বাতিল',
      'continueAction': 'এগিয়ে যান',
      'history': 'অডিট ইতিহাস',
      'snapshots': 'গণনার স্ন্যাপশট',
      'createSnapshot': 'ইনপুট স্ন্যাপশট স্থির করুন',
      'snapshotCreated': 'অপরিবর্তনীয় ইনপুট স্ন্যাপশট তৈরি হয়েছে',
      'inputHash': 'SHA-256 ইনপুট হ্যাশ',
      'schemaVersion': 'স্কিমা ভার্সন',
      'clientCreated': 'ক্লায়েন্ট তৈরি হয়েছে',
      'clientUpdated': 'ক্লায়েন্টের তথ্য পরিবর্তিত হয়েছে',
      'birthRecordCreated': 'জন্ম রেকর্ড তৈরি হয়েছে',
      'birthRecordUpdated': 'জন্ম রেকর্ড পরিবর্তিত হয়েছে',
      'settingsUpdated': 'গণনার সেটিংস পরিবর্তিত হয়েছে',
      'noHistory': 'কোনো অডিট ঘটনা নেই',
      'noSnapshots': 'এখনও কোনো গণনার স্ন্যাপশট নেই',
      'immutableNote': 'স্ন্যাপশট স্থায়ী; এটি সম্পাদনা বা মুছে ফেলা যাবে না।',
      'consultations': 'পরামর্শসমূহ',
      'consultationSubject': 'প্রশ্ন / পরামর্শের বিষয়',
      'consultationCategory': 'বিভাগ',
      'selectBirthRecord': 'জন্ম রেকর্ড নির্বাচন করুন',
      'selectSystems': 'জ্যোতিষ পদ্ধতি নির্বাচন করুন',
      'general': 'সাধারণ',
      'career': 'পেশা',
      'business': 'ব্যবসা',
      'marriage': 'বিবাহ',
      'finance': 'অর্থ',
      'education': 'শিক্ষা',
      'health': 'স্বাস্থ্য',
      'property': 'সম্পত্তি',
      'children': 'সন্তান',
      'travelRelocation': 'ভ্রমণ / স্থানান্তর',
      'draft': 'খসড়া',
      'reviewed': 'পর্যালোচিত',
      'finalized': 'চূড়ান্ত',
      'selectAtLeastOne': 'অন্তত একটি জ্যোতিষ পদ্ধতি নির্বাচন করুন',
      'consultationCreated': 'পরামর্শ তৈরি হয়েছে',
      'consultationUpdated': 'পরামর্শ পরিবর্তিত হয়েছে',
      'calculationOutputCreated': 'ভার্সনযুক্ত গণনার ফল তৈরি হয়েছে',
      'noConsultations': 'এখনও কোনো পরামর্শ নেই',
      'enginePending': 'গণনা ইঞ্জিনের ফল অপেক্ষমাণ',
      'consultationDetails': 'পরামর্শের বিস্তারিত',
      'editConsultation': 'পরামর্শ সম্পাদনা করুন',
      'prepareInput': 'গণনার ইনপুট প্রস্তুত করুন',
      'inputReady': 'গণনার ইনপুট স্ন্যাপশট প্রস্তুত',
      'idempotentInputNote': 'জন্মতথ্য ও সেটিংস অপরিবর্তিত থাকলে আগের স্ন্যাপশটই ব্যবহৃত হবে।',
      'calculationOutputs': 'গণনার ফলসমূহ',
      'outputAvailable': 'যাচাইকৃত গণনার ফল প্রস্তুত',
      'engineVersion': 'ইঞ্জিন ভার্সন',
      'outputHash': 'ফলের SHA-256 হ্যাশ',
      'reviewRequiresOutput': 'পর্যালোচনার আগে যাচাইকৃত ইঞ্জিনের ফল প্রয়োজন।',
      'markReviewed': 'পর্যালোচিত হিসেবে চিহ্নিত করুন',
      'reopenDraft': 'খসড়া হিসেবে পুনরায় খুলুন',
      'finalizeConsultation': 'পরামর্শ চূড়ান্ত করুন',
      'finalizedLocked': 'চূড়ান্ত পরামর্শ লক করা হয়েছে',
      'statusUpdated': 'পরামর্শের অবস্থা পরিবর্তিত হয়েছে',
      'invalidTransition': 'এই অবস্থার পরিবর্তন অনুমোদিত নয়',
      'calculatedFieldsLocked': 'গণনার পরে জন্ম রেকর্ড ও নির্বাচিত পদ্ধতি লক থাকবে।',
      'addGemstoneRemedy': 'গ্রহরত্ন সমাধান যোগ করুন',
      'editGemstoneRemedy': 'গ্রহরত্ন সমাধান সম্পাদনা করুন',
      'noGemstoneRemedies': 'এখনও কোনো গ্রহরত্ন সমাধান নথিভুক্ত নেই',
      'planet': 'সংশ্লিষ্ট গ্রহ',
      'sun': 'সূর্য',
      'moon': 'চন্দ্র',
      'mars': 'মঙ্গল',
      'mercury': 'বুধ',
      'jupiter': 'বৃহস্পতি',
      'venus': 'শুক্র',
      'saturn': 'শনি',
      'rahu': 'রাহু',
      'ketu': 'কেতু',
      'primaryGemstone': 'প্রধান রত্ন',
      'substituteGemstone': 'বিকল্প রত্ন (ঐচ্ছিক)',
      'gemstoneWeight': 'ওজন',
      'weightUnit': 'ওজনের একক',
      'carat': 'ক্যারেট',
      'ratti': 'রতি',
      'invalidGemstoneWeight': 'ওজন ০-এর বেশি এবং ১০০-এর মধ্যে লিখুন',
      'metal': 'ধাতু',
      'finger': 'আঙুল',
      'wearingDay': 'ধারণের দিন',
      'wearingInstructions': 'প্রচলিত ধারণবিধি',
      'astrologicalReason': 'জ্যোতিষীয় কারণ',
      'evidenceReferences': 'চার্টের প্রমাণসূত্র',
      'evidenceHint': 'প্রতি লাইনে একটি, অথবা কমা দিয়ে আলাদা করুন',
      'cautions': 'সতর্কতা ও যাচাই মন্তব্য',
      'remedyDecision': 'জ্যোতিষীর সিদ্ধান্ত',
      'approved': 'অনুমোদিত',
      'rejected': 'প্রত্যাখ্যাত',
      'saveRemedy': 'গ্রহরত্ন সমাধান সংরক্ষণ করুন',
      'remedySaved': 'গ্রহরত্ন সমাধান অফলাইনে সংরক্ষিত হয়েছে',
      'approvalRequiresEvidence': 'অনুমোদনের আগে অন্তত একটি চার্ট প্রমাণসূত্র প্রয়োজন',
      'approvalRequiresOutput': 'অনুমোদনের আগে যাচাইকৃত গণনার ফল প্রয়োজন',
      'remedyTraditionalDisclaimer': 'এটি প্রচলিত জ্যোতিষ নির্দেশনা। চার্টের প্রমাণ, রত্নের সত্যতা ও ব্যক্তিগত উপযোগিতা যাচাই করুন; চিকিৎসা বা নিশ্চিত ফলের প্রতিশ্রুতি দেবেন না।',
      'ephemerisStatus': 'অফলাইন এফেমেরিসের অবস্থা',
      'ephemerisNotConfigured': 'নিষ্ক্রিয়—যাচাইকৃত offline astronomical backend এখনও যুক্ত হয়নি।',
      'ephemerisOpenEngine': 'MIT Astronomy Engine backend সক্রিয়',
      'runKundliAnalysis': 'কুণ্ডলী বিচার চালান',
      'kundliAnalysisRunning': 'গণনা ও যাচাইকৃত নিয়ম প্রয়োগ হচ্ছে…',
      'kundliAnalysisReady': 'কুণ্ডলী গণনা ও বিচারের খসড়া অফলাইনে সংরক্ষিত হয়েছে',
      'kundliAnalysisFailed': 'কুণ্ডলী বিচার সম্পূর্ণ করা যায়নি',
      'vedicSystemRequired': 'কুণ্ডলী বিচার চালাতে এই পরামর্শে বৈদিক / পরাশরী পদ্ধতি নির্বাচন করুন।',
      'kundliAnalysis': 'কুণ্ডলী বিচারের খসড়া',
      'noKundliAnalysis': 'এখনও কোনো কুণ্ডলী বিচারের খসড়া তৈরি হয়নি।',
      'analysisVersions': 'অপরিবর্তনীয় ভার্সন',
      'professionalReviewRequired': 'শুধু খসড়া—প্রতিটি সিদ্ধান্ত ও সমাধান প্রার্থী পেশাদার জ্যোতিষীকে যাচাই করতে হবে।',
      'chartEvidence': 'চার্টের প্রমাণ ও নিয়মের পথ',
      'remedyCandidates': 'আচরণগত সমাধান প্রার্থী',
      'gemstoneCandidateReview': 'রত্ন প্রার্থী ও contraindication পর্যালোচনা',
      'eligible': 'পেশাদার পর্যালোচনার জন্য Eligible',
      'contraindicated': 'Strengthening-এর জন্য Contraindicated',
      'insufficientEvidence': 'প্রমাণ অপর্যাপ্ত',
      'analysisWarnings': 'পরিধি ও নিরাপত্তা সতর্কতা',
      'lagnaJudgment': 'লগ্ন ও লগ্নেশ বিচার',
      'yogaDoshaReview': 'যোগ ও দোষের গঠন পর্যালোচনা',
      'd1D9Agreement': 'D1–D9 নবাংশের মিল',
      'd10CareerReview': 'D10 দশাংশ কর্মজীবন বিচার',
      'shadbalaReview': 'ষড়বল শক্তি ও threshold',
      'ashtakavargaReview': 'অষ্টকবর্গ ভাব-সমর্থন',
      'vimshottariTiming': 'বিমশোত্তরী মহাদশা–অন্তর্দশার সময়কাল',
      'dashaTimeline': 'বিমশোত্তরী দশার সময়রেখা',
      'dashaTimelineSummary': 'চার্টভিত্তিক বিস্তারিত ব্যাখ্যা এবং বর্তমান, অতীত ও ভবিষ্যৎ filter-সহ জন্ম-পরবর্তী প্রত্যন্তরদশার সময়রেখা দেখুন।',
      'currentDasha': 'বর্তমান',
      'pastDasha': 'অতীত',
      'futureDasha': 'ভবিষ্যৎ',
      'noCurrentDasha': 'এই ১২০ বছরের চক্রে বর্তমানে কোনো সময়কাল নেই।',
      'noDashaPeriods': 'এই filter-এ কোনো দশার সময়কাল নেই।',
      'pratyantarTimingCaution': 'প্রত্যন্তরদশা chart activation-এর সময়সীমা সূক্ষ্ম করে এবং বিস্তারিত review layer দেয়। ঘটনা নিশ্চিত করতে chart promise, consultation question ও গোচর যাচাই এখনও প্রয়োজন।',
      'antardashaTendency': 'মূল অন্তর্দশার প্রবণতা',
      'pratyantarOwnTendency': 'প্রত্যন্তরদশার নিজস্ব প্রবণতা',
      'pratyantarDetailedInterpretation': 'প্রত্যন্তরদশার বিস্তারিত ব্যাখ্যা',
      'pratyantarTriggerRelation': 'তাৎক্ষণিক trigger relation',
      'pratyantarTrigger_reinforcing': 'বৃহত্তর MD/AD direction-কে শক্তিশালী করছে',
      'pratyantarTrigger_countertrend': 'বৃহত্তর MD/AD direction-এর বিপরীত প্রবণতা',
      'pratyantarTrigger_neutral': 'অতিরিক্ত directional trigger নেই',
      'threeLevelDashaSynthesis': 'তিন-স্তরের দশা-সংশ্লেষ',
      'score': 'স্কোর',
      'weightedScore': 'ভারযুক্ত স্কোর',
      'dashaWeightFormula': 'মহাদশা ×৩ + অন্তর্দশা ×২ + প্রত্যন্তরদশা ×১',
      'activatedLifeAreas': 'পুনর্বলিত জীবনক্ষেত্র',
      'contradictoryDashaSignals': 'তিন দশাপতির মধ্যে বিপরীত সংকেত থাকায় সম্মিলিত ফল মিশ্র রাখা হয়েছে।',
      'pratyantarNoJudgment': 'এই পুরোনো সময়কালের সঙ্গে অন্তর্দশার বিচার যুক্ত নেই। পেশাদার পর্যালোচনা আবশ্যক।',
      'reviewRequired': 'পেশাদার যাচাই',
      'twelveHouseJudgment': 'বারোটি ভাবের অবস্থা',
      'detailedLifeAreaJudgment': 'জীবনক্ষেত্রের বিস্তারিত সমন্বিত বিচার',
      'functionalPlanetRoles': 'গ্রহের কার্যকর প্রবণতা',
      'houseOccupancy': 'ভাবস্থিত গ্রহসমূহ',
      'parashariAspects': 'পরাশরী পূর্ণ রাশিদৃষ্টি',
      'planetConditions': 'অস্তাঙ্গতা ও বক্রী অবস্থা',
      'aspectSynthesis': 'বহু-দৃষ্টির সম্মিলিত বিচার',
      'conjunctions': 'একই-রাশির গ্রহসংযোগ',
      'friendshipAndMoolatrikona': 'গ্রহমৈত্রী ও মূলত্রিকোণ',
      'planetaryWarReview': 'গ্রহযুদ্ধ পর্যালোচনা',
      'overall': 'সামগ্রিক',
      'self': 'স্বভাব ও প্রাণশক্তি',
      'family': 'পরিবার ও বাকশক্তি',
      'communication': 'যোগাযোগ ও সাহস',
      'siblings': 'ভাইবোন',
      'obstacles': 'বাধা, ঋণ ও বিরোধ',
      'longevity': 'আয়ু ও রূপান্তর',
      'fortune': 'ভাগ্য ও ধর্ম',
      'gains': 'লাভ ও যোগাযোগবৃত্ত',
      'expenses': 'ব্যয় ও নির্জনতা',
      'spirituality': 'আধ্যাত্মিকতা',
      'supportive': 'সহায়ক',
      'challenging': 'চ্যালেঞ্জিং',
      'mixed': 'মিশ্র',
      'low': 'কম নির্ভরযোগ্যতা',
      'medium': 'মাঝারি নির্ভরযোগ্যতা',
      'high': 'উচ্চ নির্ভরযোগ্যতা',
      'generateProfessionalReport': 'পেশাদার রিপোর্ট তৈরি করুন',
      'professionalReports': 'পেশাদার পরামর্শ রিপোর্ট',
      'professionalReportPreview': 'পেশাদার রিপোর্ট প্রিভিউ',
      'professionalReportCreated': 'পেশাদার রিপোর্ট snapshot তৈরি হয়েছে',
      'professionalReportReady': 'পেশাদার রিপোর্ট তৈরি ও অফলাইনে সংরক্ষিত হয়েছে',
      'professionalReportFailed': 'পেশাদার রিপোর্ট তৈরি করা যায়নি',
      'noProfessionalReports': 'এখনও কোনো পেশাদার রিপোর্ট snapshot তৈরি হয়নি।',
      'reportHash': 'রিপোর্ট SHA-256',
      'reportAsOf': 'রিপোর্টের সময়সীমা',
      'reportSafetyWarnings': 'রিপোর্টের নিরাপত্তা ও পরিধি সতর্কতা',
      'exportReportPdf': 'PDF এক্সপোর্ট / শেয়ার',
      'exportReportDocx': 'DOCX এক্সপোর্ট / শেয়ার',
      'reportExporting': 'এক্সপোর্ট ফাইল তৈরি হচ্ছে…',
      'reportExportReady': 'রিপোর্ট এক্সপোর্ট অফলাইনে তৈরি হয়েছে',
      'reportExportFailed': 'রিপোর্ট এক্সপোর্ট তৈরি করা যায়নি',
      'reportExportHash': 'এক্সপোর্ট SHA-256',
      'reportExportNote': 'PDF/DOCX ফাইল এই immutable report snapshot থেকেই তৈরি হয়। Source report hash exported document-এর মধ্যে সংরক্ষিত থাকে।',
      'reportApprovalTitle': 'পেশাদার অনুমোদন ও সাইন-অফ',
      'reportNotApproved': 'এখনও ক্লায়েন্ট ডেলিভারির জন্য অনুমোদিত নয়',
      'reportApproved': 'অনুমোদিত ও লক করা হয়েছে',
      'approveReport': 'রিপোর্ট পর্যালোচনা ও অনুমোদন করুন',
      'approvalImmutableNote': 'এই report snapshot-এর approval স্থায়ী। পেশাদার মতামত বদলাতে হলে নতুন report snapshot তৈরি করুন।',
      'approvalElectronicDisclosure': 'এটি app-এর ভিতরের practitioner electronic sign-off; certificate-backed cryptographic/digital signature নয়।',
      'practitionerName': 'Practitioner-এর নাম',
      'practitionerDesignation': 'পদবি / পেশাদার পরিচয়',
      'credentialReference': 'Credential / registration reference (ঐচ্ছিক)',
      'approvalDecision': 'অনুমোদনের সিদ্ধান্ত',
      'approvedForClientDelivery': 'ক্লায়েন্ট ডেলিভারির জন্য অনুমোদিত',
      'approvedWithReservations': 'সতর্কতা/শর্তসহ অনুমোদিত',
      'approvalNote': 'অনুমোদন নোট',
      'approvalNoteRequired': 'সতর্কতা/শর্তসহ অনুমোদনের ক্ষেত্রে note আবশ্যক।',
      'approvalAttestation': 'আমি এই immutable report snapshot পর্যালোচনা করেছি এবং বুঝছি এই action edit বা undo করা যাবে না।',
      'approvalAttestationRequired': 'সাইন করার আগে approval acknowledgement নিশ্চিত করুন।',
      'approvalSave': 'অনুমোদন করে রিপোর্ট লক করুন',
      'approvalSaving': 'Immutable approval সংরক্ষণ হচ্ছে…',
      'approvalSaved': 'পেশাদার approval সংরক্ষিত ও লক হয়েছে',
      'approvalFailed': 'পেশাদার approval সংরক্ষণ করা যায়নি',
      'approvedAt': 'অনুমোদনের সময় (UTC)',
      'approvalHash': 'Approval SHA-256',
      'signedReportHash': 'Signed-report SHA-256',
      'approvalContract': 'Approval contract',
      'signedReportVerificationQr': 'Signed report verification QR',
      'verifySignedReport': 'Signed report যাচাই করুন',
      'copyVerificationPayload': 'Verification payload কপি করুন',
      'verificationPayloadCopied': 'Verification payload কপি হয়েছে',
      'signedReportVerifierTitle': 'Signed report verifier',
      'signedReportVerifierIntro': 'ASTRO LOGIC signed-report verification payload paste করুন, অথবা locally signed report থেকে এই screen খুলুন। Immutable local record-এর সঙ্গে সম্পূর্ণ offline যাচাই হবে।',
      'verificationPayload': 'Verification payload',
      'verificationPayloadHint': 'Report QR-এ থাকা compact JSON payload paste করুন।',
      'pasteAndVerify': 'Paste করে যাচাই করুন',
      'verificationScopeDisclosure': 'শুধু structurally valid QR/payload practitioner-এর পরিচয় বা report authenticity প্রমাণ করে না। পূর্ণ verification-এর জন্য এই ASTRO LOGIC database-এ matching immutable report ও approval record থাকতে হবে।',
      'verificationContract': 'Verification contract',
      'verificationVerifiedLocal': 'Local immutable record-এর সঙ্গে যাচাই সফল',
      'verificationNoLocalRecord': 'Payload valid, কিন্তু matching local record নেই',
      'verificationMismatchDetected': 'Mismatch বা tamper ধরা পড়েছে',
      'verificationInvalidPayload': 'Verification payload invalid বা unsupported',
      'verificationPayloadParseFailed': 'Supported verification contract অনুযায়ী payload parse করা যায়নি।',
      'verificationPayloadHashMismatch': 'Payload-এর report/approval hash থেকে signed-report hash মেলেনি।',
      'verificationPayloadInternallyConsistent': 'Supported hash contract অনুযায়ী payload internally consistent।',
      'verificationAuthenticityNotEstablished': 'Matching local immutable record পাওয়া যায়নি; practitioner authenticity established নয়।',
      'verificationReportIdentityMismatch': 'Local report identity payload-এর সঙ্গে মিলছে না।',
      'verificationStoredReportHashMismatch': 'Stored report content তার persisted report hash-এর সঙ্গে আর মিলছে না।',
      'verificationReportHashVerified': 'Immutable report content recompute করে stored report hash-এর সঙ্গে মিলেছে।',
      'verificationLocalApprovalMissing': 'Matching local report-এর corresponding immutable approval record নেই।',
      'verificationApprovalContractInvalid': 'Stored approval contract metadata invalid বা unsupported।',
      'verificationApprovalIdentityMismatch': 'Local approval metadata payload-এর সঙ্গে মিলছে না।',
      'verificationStoredApprovalHashMismatch': 'Stored approval metadata তার approval hash-এর সঙ্গে আর মিলছে না।',
      'verificationApprovalHashVerified': 'Immutable approval metadata recompute করে stored approval hash-এর সঙ্গে মিলেছে।',
      'verificationStoredSignedHashMismatch': 'Local signed-report hash report ও approval hash থেকে recompute হচ্ছে না।',
      'verificationSignedHashVerified': 'Report ও approval hash থেকে signed-report hash সঠিকভাবে recompute হয়েছে।',
      'verificationLocalImmutableRecordMatched': 'Local database-এর report ও approval record এই payload-এর সঙ্গে মিলেছে।',
      'reportStatus_available': 'উপলব্ধ',
      'reportStatus_limited': 'সীমিত / curated',
      'reportStatus_unavailable': 'অনুপলব্ধ',
      'confidence': 'নির্ভরযোগ্যতা',
    },
  };

  static String of(BuildContext context, String key) {
    final language = Localizations.localeOf(context).languageCode;
    return _values[language]?[key] ?? _values['en']![key] ?? key;
  }
}
